menu:

- {name: 'research', url: '/research'}
- {name: 'projects', url: '/projects'}
# - {name: 'courses', url: '/courses'}
# - {name: 'cv', url: '/cv'}
- {name: 'experience', url: '/experience'}

contacts:
  - name: "SUN Fengfei"
    email: "sunfengfei@u.nus.edu"
    address: "Singapore"
    phone: "(+65) 80675057"